"""initial schema

Revision ID: 1448de6b11e7
Revises: 
Create Date: 2026-07-09 12:41:11.459228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1448de6b11e7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ragione_sociale', sa.String(length=255), nullable=False),
    sa.Column('indirizzo', sa.String(length=255), nullable=True),
    sa.Column('codice_azienda', sa.String(length=32), nullable=True),
    sa.Column('inail_aut', sa.String(length=32), nullable=True),
    sa.Column('inail_del', sa.String(length=32), nullable=True),
    sa.Column('inail_sede', sa.String(length=32), nullable=True),
    sa.Column('posizione_inps', sa.String(length=64), nullable=True),
    sa.Column('pat_inail', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ragione_sociale', 'codice_azienda', name='uq_company_identity')
    )
    op.create_table('employee',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cognome_nome', sa.String(length=255), nullable=False),
    sa.Column('codice_fiscale', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codice_fiscale')
    )
    op.create_table('payroll_period',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mese', sa.Integer(), nullable=False),
    sa.Column('anno', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=32), nullable=False),
    sa.Column('label_originale', sa.String(length=64), nullable=True),
    sa.CheckConstraint('mese >= 1 AND mese <= 12', name='ck_period_mese'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mese', 'anno', 'tipo', name='uq_period')
    )
    op.create_table('schema_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('employment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('matricola', sa.String(length=32), nullable=True),
    sa.Column('data_assunzione', sa.Date(), nullable=True),
    sa.Column('data_cessazione', sa.Date(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'company_id', 'valid_from', name='uq_employment_span')
    )
    op.create_table('payroll_document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('template_name', sa.String(length=64), nullable=False),
    sa.Column('parser_version', sa.String(length=32), nullable=False),
    sa.Column('source_used_ocr', sa.Boolean(), nullable=False),
    sa.Column('processed_path', sa.String(length=512), nullable=True),
    sa.Column('error_path', sa.String(length=512), nullable=True),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('period_id', sa.UUID(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['payroll_period.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'company_id', 'period_id', name='uq_document_logical_key'),
    sa.UniqueConstraint('sha256')
    )
    op.create_index(op.f('ix_payroll_document_company_id'), 'payroll_document', ['company_id'], unique=False)
    op.create_index(op.f('ix_payroll_document_employee_id'), 'payroll_document', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_document_period_id'), 'payroll_document', ['period_id'], unique=False)
    op.create_index(op.f('ix_payroll_document_status'), 'payroll_document', ['status'], unique=False)
    op.create_table('anomaly',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=64), nullable=False),
    sa.Column('severita', sa.String(length=16), nullable=False),
    sa.Column('messaggio', sa.Text(), nullable=False),
    sa.Column('campo', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severita IN ('info','warning','error')", name='ck_anomaly_severita'),
    sa.ForeignKeyConstraint(['document_id'], ['payroll_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_document_id'), 'anomaly', ['document_id'], unique=False)
    op.create_table('audit_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['payroll_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_event_document_id'), 'audit_event', ['document_id'], unique=False)
    op.create_index(op.f('ix_audit_event_run_id'), 'audit_event', ['run_id'], unique=False)
    op.create_table('leave_balance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=32), nullable=False),
    sa.Column('maturato', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.Column('goduto', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.Column('residuo', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.Column('residuo_ap', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['payroll_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_balance_document_id'), 'leave_balance', ['document_id'], unique=False)
    op.create_table('pay_line',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('codice_causale', sa.String(length=16), nullable=True),
    sa.Column('descrizione', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=32), nullable=False),
    sa.Column('is_recognized', sa.Boolean(), nullable=False),
    sa.Column('importo_base', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.Column('quantita', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.Column('unita', sa.String(length=8), nullable=True),
    sa.Column('aliquota', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.Column('trattenuta', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.Column('competenza', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['payroll_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pay_line_document_id'), 'pay_line', ['document_id'], unique=False)
    op.create_table('payroll_totals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('imponibile_inps', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.Column('imponibile_inail', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.Column('imponibile_irpef', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.Column('totale_competenze', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.Column('totale_trattenute', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.Column('netto_mese', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('banca', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['payroll_document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_table('raw_extraction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('words', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unrecognized_rows', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('font_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ocr_used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['payroll_document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_table('tax',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('imponibile_irpef', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.Column('irpef_lorda', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.Column('detrazioni_lav_dip', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.Column('ritenute_irpef', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.Column('addizionale_regionale', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.Column('addizionale_regionale_regione', sa.String(length=64), nullable=True),
    sa.Column('addizionale_comunale', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.Column('acconto_addizionale_comunale', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['payroll_document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_table('tfr',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('retribuzione_utile_tfr', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.Column('quota_tfr_fondi', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.Column('rivalutazione', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.Column('imponibile_rivalutazione', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.Column('quota_anno', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.Column('anticipi', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['payroll_document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tfr')
    op.drop_table('tax')
    op.drop_table('raw_extraction')
    op.drop_table('payroll_totals')
    op.drop_index(op.f('ix_pay_line_document_id'), table_name='pay_line')
    op.drop_table('pay_line')
    op.drop_index(op.f('ix_leave_balance_document_id'), table_name='leave_balance')
    op.drop_table('leave_balance')
    op.drop_index(op.f('ix_audit_event_run_id'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_document_id'), table_name='audit_event')
    op.drop_table('audit_event')
    op.drop_index(op.f('ix_anomaly_document_id'), table_name='anomaly')
    op.drop_table('anomaly')
    op.drop_index(op.f('ix_payroll_document_status'), table_name='payroll_document')
    op.drop_index(op.f('ix_payroll_document_period_id'), table_name='payroll_document')
    op.drop_index(op.f('ix_payroll_document_employee_id'), table_name='payroll_document')
    op.drop_index(op.f('ix_payroll_document_company_id'), table_name='payroll_document')
    op.drop_table('payroll_document')
    op.drop_table('employment')
    op.drop_table('schema_version')
    op.drop_table('payroll_period')
    op.drop_table('employee')
    op.drop_table('company')
    # ### end Alembic commands ###
