"""aggiunge imponibile previdenziale non arrotondato a tax

Revision ID: 61f9220692dd
Revises: 92192e31a5b0
Create Date: 2026-07-17 09:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61f9220692dd'
down_revision: Union[str, Sequence[str], None] = '92192e31a5b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tax', sa.Column('imponibile_previdenziale_non_arrotondato', sa.Numeric(precision=14, scale=5), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tax', 'imponibile_previdenziale_non_arrotondato')
    # ### end Alembic commands ###
