"""aggiunge campi annuali tax/tfr per riepilogo tredicesima sap hr

Revision ID: 92192e31a5b0
Revises: 8c1ff2c33db2
Create Date: 2026-07-16 14:59:54.567714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92192e31a5b0'
down_revision: Union[str, Sequence[str], None] = '8c1ff2c33db2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tax', sa.Column('imponibile_fiscale_annuo', sa.Numeric(precision=14, scale=5), nullable=True))
    op.add_column('tax', sa.Column('imposta_lorda_annua', sa.Numeric(precision=14, scale=5), nullable=True))
    op.add_column('tax', sa.Column('imposta_dovuta_annua', sa.Numeric(precision=14, scale=5), nullable=True))
    op.add_column('tax', sa.Column('imposta_pagata_annua', sa.Numeric(precision=14, scale=5), nullable=True))
    op.add_column('tax', sa.Column('imp_inps_progr_annuo', sa.Numeric(precision=14, scale=5), nullable=True))
    op.add_column('tax', sa.Column('ctr_inps_progr_annuo', sa.Numeric(precision=14, scale=5), nullable=True))
    op.add_column('tax', sa.Column('ctr_dip_inps_progr_annuo', sa.Numeric(precision=14, scale=5), nullable=True))
    op.add_column('tax', sa.Column('cong_credito_annuo', sa.Numeric(precision=14, scale=5), nullable=True))
    op.add_column('tax', sa.Column('cong_debito_annuo', sa.Numeric(precision=14, scale=5), nullable=True))
    op.add_column('tfr', sa.Column('retribuzione_utile_tfr_annua', sa.Numeric(precision=14, scale=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tfr', 'retribuzione_utile_tfr_annua')
    op.drop_column('tax', 'cong_debito_annuo')
    op.drop_column('tax', 'cong_credito_annuo')
    op.drop_column('tax', 'ctr_dip_inps_progr_annuo')
    op.drop_column('tax', 'ctr_inps_progr_annuo')
    op.drop_column('tax', 'imp_inps_progr_annuo')
    op.drop_column('tax', 'imposta_pagata_annua')
    op.drop_column('tax', 'imposta_dovuta_annua')
    op.drop_column('tax', 'imposta_lorda_annua')
    op.drop_column('tax', 'imponibile_fiscale_annuo')
    # ### end Alembic commands ###
